server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: w5103265
    driver-class-name: com.mysql.cj.jdbc.Driver